### ISSUE TITLE
Hackathons.com Roadmap

### ISSUE THREAD

**Issue by rodrigoargumedo** [hackathons-com/Rails-MongoDB-Devise-test#1]
Here, this is what I have so far and let me know if guys want more features.

- [x] Devise::User Implementation
- [ ] Profiles 
- [x] Blog
- [ ] Admin panel
- [ ] Google Maps integration
- [x] Travis-CI integration
- [ ] Events
- [ ] Hackathon attendance group (i.e. if someone got accepted to a hackathon, automatically joins the attending group to discuss and form teams)
- [ ] Stack Exchange API (for use of Stack Overflow API?)
- [x] Facebook Login
- [x] ERB to Slim #2
- [x] Merge @robbyoconnor's upcoming pull request. See: #3
- [ ] Projects (aka Hacks)
- [ ] Meetups
- [ ] MySQL or PostgreSQL database integration with MongoDB for even better relational database? #4 (Will not be in this version)
- [ ] Unit Testing for Rails and Devise controllers and models? (assigned to @jjman505)
- [ ] Legal Compliance System (DCMA, logs, etc.)
- [x] RSpec migration for test
- [x] Mongoid 5.0.0? (Nope, this has a lot of bugs that require to be fixed, might reconsider in the future)
- [x] Markdown support #6 
- [ ] Realtime chat implementation

Things to consider later:

* Messages
* API
* Notification System

cc: @hackathons-com/collaborators @hackathons-com/canary-team @hackathons-com/beta-testers @hackathons-com/canary-team

**Comment by rodrigoargumedo** [comment]
@jjman505 @robbyoconnor How would think about this? (See above conversation or click on the email link to view)
